### ISSUE TITLE
FixtureFactories with new types from plugins

### ISSUE THREAD

**Issue by gringlas** [vierge-noire/cakephp-fixture-factories#127]
When I try to create entities with a FixtureFactory on an entity which got added new DataTypes through a plugin I will get an exception, i.e.  `InvalidArgumentException : Unknown type "upload.file"` 
In my case I'm using the [UploadBehaviorPlugon](https://packagist.org/packages/josegonzalez/cakephp-upload) in my ImagesTable, which declares a new Type 'upload.file' in its Plugin.php. I then wanted to use a ImageFactory to create an entity, like: 
```
$image = ImageFactory::make([
            'filename' =>  'path.jpg',
            'path' => 'my/path'
        ])->persist();
``` 
I had to add `TypeFactory::map('upload.file', FileType::class);` to my ImagesTableTest class, to got it working. Is this the intended way, or is this an issue?

Thanks for this great plugin!

**Comment by pabloelcolombiano** [comment]
Glad you are enjoying the plugin!

This is specific to the Uploaded plugin, and should probably not be handled by the factories.

What you could do is check in the `ImageFactory::setDefaultTemplate()` method if the type exists (`TypeFactory::getMap('upload.file')`), and if not found, `TypeFactory::map('upload.file', FileType::class);`.

This way, your issue is solved for all the tests involving that factory.

**Comment by gringlas** [comment]
This is working like a charme. Thank you! :)
