### ISSUE TITLE
Doc corrections

### ISSUE THREAD

**Issue by MolbioUnige** [vierge-noire/cakephp-fixture-factories#28]
It concerns `docs/setup.md`

To ignore connections the key should be `TestSuiteLightIgnoredConnections` instead of `TestFixtureIgnoredConnections` as such:

```
<?php

return [   
    'TestSuiteLightIgnoredConnections' => [
        'test_foo_connection_to_be_ignored',
        'test_bar_connection_to_be_ignored',
        ...
    ],
];
```

and, for people like me, I would also add some instruction on how to load `fixture_factories.php` as this was not obvious for me.

```
// in config/bootstrap.php
Configure::load('fixture_factories', 'default')
```

**Comment by pabloelcolombiano** [comment]
@MolbioUnige Thank you for the correction. I have modified that in the docs. Note that if the config file is named `config/test_suite_light.php`, it will be automatically loaded by the plugin, I you do not have to care loading it. The problem was that the docs mentioned a deprecated config name. This is now fixed.
