### ISSUE TITLE
[Feature request] - Add a `FactoryAwareTrait` to ease getting factory

### ISSUE THREAD

**Issue by liqueurdetoile** [vierge-noire/cakephp-fixture-factories#59]
Hi,

I've created for myself a little helper trait to ease getting a factory and I'm wondering if it may be of some interest to include one in this package.

Instead of doing

```php
<?php
use App\Tests\Factory\FooFactory;
use App\Tests\Factory\BarFactory;
use App\Tests\Factory\BazFactory;

class MyTest extends TestCase
{
     public function testFoo(): void
     {
        FooFactory::make()->...;
     }

     public function testBar(): void
     {
        BarFactory::make()->...;
     }

     public function testBaz(): void
     {
        BazFactory::make()->...;
     }
}
```

I'm doing this :

```php
<?php
use App\Tests\FactoryAwareTrait;

class MyTest extends TestCase
{
    use FactoryAwareTrait;
    
    public function testFoo(): void
    {
      $this->getFactory('foo')->...;
    }

    public function testBar(): void
    {
      $this->getFactory('bars')->...;
    }

     public function testBaz(): void
     {
        $this->getFactory('Bazes')->...;
     }
}
```
I've added some string transforms to be tolerant against cases and plurals. I've also extended my base test case to include trait so getFactory is available everywhere 😄 

If you're interested, here's the code or I can submit a PR

```php
<?php
declare(strict_types=1);

namespace App\Tests

use Cake\Core\Configure;
use Cake\Utility\Inflector;
use CakephpFixtureFactories\Factory\BaseFactory;

trait FactoryAwareTrait
{
    public function getFactory(string $model): BaseFactory
    {
        // Build class name
        $app = Configure::read('App.namespace') ?? 'App';
        $model = Inflector::singularize(ucfirst(strtolower($model)));
        $className = "$app\\Test\\Factory\\$model" . "Factory";

        if (class_exists($className)) {
            return $className::make();
        }

        throw new \Exception('Unable to locate Factory class for ' . $model);
    }
}

**Comment by pabloelcolombiano** [comment]
Hi @liqueurdetoile ,

glad to see you active on this repository too!

The advantage of the static call as featured in the package is that:
1. a good IDE autocompletes everything from you. You solution implies to type 'foo', increasing the risk of typo.
2. factories do not share states as such. Your notation looks like CakePHP tables (and components) awareness notation, which makes sense in the context of a repository. But this is not the case for the factories. There are no repositories, each factory lives for itself.

Correct me if I foresaw any advantage of your notation.

I'll mention my fellow colleagues @pakacuda @vidrascu001 to have their point of view, we take decisions together and might see some potential in your proposal.

**Comment by liqueurdetoile** [comment]
Hi @pabloelcolombiano 

Thanks for your welcome 😄 

I understand your point of view. Here's some elements to respond :

1. This trait only brings another way to achieve the same thing, not replacing it. About the typo, I think the trait is more opened as you can type 'foo', 'Foo', 'foos', 'Foos' without any trouble. When starting to use cakephp-fixture-factories, I sometimes find myself staring to type  `FoosFactory` instead of `FooFactory` due to old habit with fixtures : `app.Foos` and not `app.Foo`.

2. As i see it, a factory is somehow linked to a model because they are baked from them and use associations to bring up data (that's the great thing in my opinion). I think the trait naming makes sense as some of the 'aware' stuff in cakephp relies on class loading and not on any registry (ModelAwareTrait, MailerAwareTrait for instance).

I must say it's more a question of feeling than anything else. I like to have things as less verbose as possible.

**Comment by pabloelcolombiano** [comment]
Our main concern when developing the package with @pakacuda has always been to optimize the developer experience. So if you think that the FactoryAwareTrait can enhance your coding experience, I am O.K. with it.

1. This said, I do not see how you end up making typos with the static call, unless you use a very basic IDE. I made a simple demonstration in [this video](https://www.youtube.com/watch?v=PNA1Ck2-nVc&t=1350s)  at around minute 22. If you type `FooFa`, your IDE should already propose you `FooFactory`.

2. In addition, you will sometimes want to create a `PremiumUserFactory` based on the `UsersTable`, probably an extension of the `UserFactory`. In this case, the FactoryAwareTrait cannot be used. This is really not a blocker to the FactoryAwareTrait, just a thought.

3. In order to better shape the implementation of the FactoryAwareTrait: you might want to have a look at this method: https://github.com/vierge-noire/cakephp-fixture-factories/blob/main/src/Util.php#L60 I think it does the same as your implementation + enables the plugin notation. I do not mind you shifting this method and its neighbors into the trait. But we should avoid having this code duplicated.

4. Again, I'll wait for my colleagues' feedback. Personaly if some users find the FactoryAwareTrait usefull in some ways, I have no objections.

**Comment by liqueurdetoile** [comment]
I'm absolutely not willing to force things. It will be fine if you decide to avoid embedding it. Again, it's more a question of feeling than a real need and I can keep it using on my own anyway. I see it more like a syntactic sugar than anything else.

1. My IDE autocompleter indeed complains about my `FoosFact...`:unamused: and then I complain myself. That's one of the reason why I've wrote this little trait and extends my base TestCase with it 😺The main reason is that it reduces verbosity of my tests.

2. I haven't think about this one. Good point. Trait could implement [`haydenpierce/class-finder`](https://packagist.org/packages/haydenpierce/class-finder) to compare lower-cased class names as a fallback before failure.

3. Sure, plugin syntax could be implemented. Maybe in a more sophisticated way if using  `class-finder`. But I can hardly see a use case for willing to load a factory from a plugin ?

**Comment by pabloelcolombiano** [comment]
Let's give it a try @liqueurdetoile.

The point 2 is actualy not an issue, your implementation will find the PremiumUser factory.

The plugin notation can be usefull. If you have models in a plugin, their factories will by convention also be located in the corresponding plugin.

My requirements on the implementation would be:
1. That the parameters passed to the `getFactory()` method be a string first, and then optional the two parameters that the make method accepts (see [here](https://github.com/vierge-noire/cakephp-fixture-factories/blob/next/src/Factory/BaseFactory.php#L124))
2. The code placed in the Util class should be re-used, and the locator trait should be applied instead of the Util class (I think mainly by the bake command)
3. The implementation should be based on the `next` branch, not from `main`.
4. A test class should extensively test the new trait.

Does this make sense?

**Comment by liqueurdetoile** [comment]
@pabloelcolombiano It seems fine. I will have a look for a PR on this basis.

**Comment by pakacuda** [comment]
Hi All,

Thanks @liqueurdetoile for your contribution ! 

Here are my thoughts : 

1. Strongly typed factories are easy to refactor, using strings is hazardous in that context.
2. Autocompletion is better, even if you have to undo/re-type something to find the targeted factory IMO. You have immediate response as you type and you can be confident that you'll get the Factory you just typed/selected. With the `getFactory` method, you have to run the code to be sure that the correct factory was found and returned, which is an additional burden.
3. In terms of verbosity, I don't see an improvement. Could you shed some light @liqueurdetoile ? I probably missed something here :)
4. We'll potentially expose the library to unexpected name resolution bugs where someone passing some model name expects 
5. Plugin syntax must be supported, for the reason @pabloelcolombiano mentioned

That said, as @pabloelcolombiano mentioned, I wouldn't be against something that the users of the library want.

**Comment by liqueurdetoile** [comment]
Hi @pakacuda,

I totally agree with you and @pabloelcolombiano that using direct classes call is precise and less versatile. A trait like that has obviously its drawbacks but brings more flexibility on the other hand because it can easily be embedded in a custom parent TestCase to be automatically included.

About verbosity feeling. I presume it's closely related to my way of working.

For instance, if I wanna check a role-based access to an API. I prefer create a test case per role with 2 tests each rather than 10 tests in a single test case. I find it useful for keeping them fine-grained to each role specificity and more easier to expand (1 more role = 1 more test case and not 30 more lines). It's also easier to target things when troubles arise, particularly on integration test case.

To achieve this, I used to split transverse and common functionalities in traits and make my recipe with them in a test case that can then be extended. For instance, I will use Cake IntegrationTestTrait and customs FactoryAwareTrait, LoginTrait and CheckLogTrait in an AccessIntegrationTestTrait. Copy/paste a template and all setup is done for a brand new test case. Just need to add adequate fixtures and write down tests.

Personally, I'm usually go on full TDD driven way when writing code so I don't care too much of a failure due to a mistyped factory name as I mostly run a narrowed bunch of tests multiple times before achieving the coding. Most of the time, in unit tests, I try to avoid using database interactions and keep them for latter and broader integration tests. Due to this habit, @pabloelcolombiano can tell how maniac I can be about overall speed in tests initialization 😄

Strictly speaking, the gain of verbosity per test case is only of 1 line per factory used between using my Trait or direct call but, as I multiply the test cases, the gain is multiplying too. Nevertheless, I can't say that using direct Factory should be a real problem in my own case.

My goal is not to convert anyone to change its way of working. As I'm feeling more comfortable with a trait, I thought I can share the idea here as some others can also feels like me. The idea is indeed to provide an alternative not a replacement.

Anyway, as you stated, it can be hard to maintain it against fancy factories names if willing to keep it tolerant against casing and plurals. I have to think about that. After all, Cake does not support it in its own fixtures system.

I thank you all for taking time to discuss it 😸, it's also helping me to self analyze my very own obsessive compulsive disorders in coding 😆.

I'll see for a PR but it can't be on the top of the list. Maybe, it's better to close this issue and follow up later in the PR itself ?

**Comment by pabloelcolombiano** [comment]
Personally I see the trait as a nice to have internally to the package, because the baking console, the association builder and maybe more later can take advantage of it.

It would not be my preferred way to instantiate factories for the reasons mentioned above, but I see no objections to add the feature for the reasons you mentioned.

Additionally, opportunities appear often while implementing a feature, so I think we should give it a try.

Btw I totally share your point that DB interactions should be banned from unit testing.

Let's keep this enhancement proposal open and ready to be implemented whenever someone has time.

**Comment by pabloelcolombiano** [comment]
This has been merged into master and shipped with the latest tag.

Thanks @liqueurdetoile for your contribution!
